### ISSUE TITLE
landmark问题

### ISSUE THREAD

**Issue by SuperJim123** [Li-Shang/FaceCapture#2]
返回的landmark大小一直为0，大哥求帮忙解决下

**Comment by lawsonsli** [comment]
将这个shape_predictor_68_face_landmarks.dat文件放到存储卡中，试一试。

**Comment by SuperJim123** [comment]
谢谢啊，感谢分享

**Comment by SuperJim123** [comment]
感觉你很厉害，方便加个QQ吗？474027915
