### ISSUE TITLE
问一下r_m和r_n的默认的来源

### ISSUE THREAD

**Issue by oyyd** [Li-Shang/FaceCapture#4]
https://github.com/Li-Shang/faceCapture/blob/9fab24cef0e712c46bef9f147dfa844d5593a847/app/src/main/java/signalprocess/facecapture/FaceDetector.java#L29

请问一下，r_m和r_n的默认取值与论文中不同，代码中这两个值的来源是根据自己的情况取的值吗？

**Comment by lawsonsli** [comment]
我记得可能有点模糊了。
亚洲人和欧美的比例不太一样，我参考的是亚洲人的脸型。应该对每个人都可以用，具体你也可以做实验调整r_m, r_n。

**Comment by oyyd** [comment]
Thanks. 

我尝试在mac上实现类似的功能，但dlib似乎对我的脸识别效果很差（用了dlib上较大的数据model），pose estimate也就很不准。
